//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpensesId { get; set; }
        public double ExpensesValue { get; set; }
        public Nullable<int> OdeyenId { get; set; }
        public string ExpenesesName { get; set; }
        public Nullable<int> ExpensesQuantity { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
