//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HackathlonDBEntities : DbContext
    {
        public HackathlonDBEntities()
            : base("name=HackathlonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupPerson> GroupPersons { get; set; }
        public virtual DbSet<Person> People { get; set; }
    }
}
